GenomeSize: 5700000
LongestReadsCov: 10  
HighQualReadsCov: 30 # not used yet => idea: select only the highest Q reads for polishing
TargetCoverageAsm: 60
HostRefGenome: /home/simon/reference_genomes/GCF_000001405.40_GRCh38.p14_genomic.fna # Default = resources/empty_mock_reference.fa

Experiment: Neuropatho_SM035_N473_plasmacytoma # 20240428_Neuropatho_Meningitis_Erreger_Borreliose_Verdacht_Liquor # Neuropatho_N1244_MB_Verdacht  # "SM0037_CMV_Voigt"
Barcodes: [
    # "N473_fastq_pass_all"
    "N473_fastq_pass_notmux"
    # "all_reads_without_barcodes_to_filter_out_carry_over"
    # "fastq_pass_1"
    # "barcode01",
    # "barcode02",
    # "barcode03",
    # "barcode04",
    # "barcode05",
    # "barcode06",
    # "barcode07",
    # "barcode08",
    # "barcode09",
    # "barcode10",
    ]
Assembler: ["canu"]  # "canu" flye
# Canu specific parameters
CanuMinInput: 0.01
CanuStopOnCov: 0.01
KrakenDB: /home/simon/Nanopore_only_assembly_and_polishing/smk_workflow/resources/databases/kraken2_standard_08gb_20240904

